title: Jinspire
email: jinwu76@gmail.com
description: Writing about curiosity, insights, and reflection.
baseurl: ""
url: "https://jinspire.dev"
goatcounter: jinspiredev  # Replace with your GoatCounter code