title: Jinspire
email: jinwu76@gmail.com
description: Writing about curiosity, insights, and reflection.
baseurl: ""
url: "https://jinspire.dev"
goatcounter: jinspiredev  # Replace with your GoatCounter code

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/