title: Jinspire
email: jinwu76@gmail.com
description: Writing about curiosity, insights, and reflection.
description_zh: 写一些好奇，感悟，与思考。
baseurl: ""
url: "https://jinspire.dev"
default_lang: zh
goatcounter: jinspiredev  # Replace with your GoatCounter code